### ISSUE TITLE
Multi-line strings such as docstrings that have the triple-quotes on a separate line

### ISSUE THREAD

**Issue by AstroMike** [yianni/py2ipynb#1]
When using triple-quoted multiline strings, if the ending triple quotes are on a separate line, then the converter fails to parse.

From this input:

[test_py2ipynb.txt](https://github.com/yianni/py2ipynb/files/160359/test_py2ipynb.txt)

I get this output:
![screen shot 2016-03-06 at 9 26 32](https://cloud.githubusercontent.com/assets/5515374/13554721/c1aa3304-e37d-11e5-899a-45f5506acc61.png)

I suspect the problem lies with the nb conversion functions that you are calling, so maybe the issue report should go elsewhere?

**Comment by gatsoulis** [comment]
Sorry, just saw your issue. Will check it out when I get a chance and see if it can be fixed from the parser side. Due to deadlines and other stuff won't be soon though.
